### ISSUE TITLE
400 errors on linkTokenCreate

### ISSUE THREAD

**Issue by brbmeyer** [merge-api/merge-sdk-typescript#30]
The following returns a 400 error when working on versions 3.0.x (this works on version 2.0.6 aside from the breaking enum change)
```
import Merge from '@mergeapi/merge-sdk-typescript'

const defaultMergeConfig = new Configuration({
  apiKey: mergeApiKey,
})

const linkApi = new Merge.HRIS.LinkTokenApi(defaultMergeConfig)
const response = await linkApi.linkTokenCreate({
  endUserDetailsRequest: {
    end_user_email_address: "test@email.com",
    end_user_organization_name: "Test",
    end_user_origin_id: "test",
    categories: [Merge.HRIS.CategoriesEnumValues.Hris],
  },
})
```

**Comment by f-huang** [comment]
A breaking change in the API has been introduced since v3.0.x, where enum values need to be wrapped in an interface.
See https://github.com/merge-api/merge-sdk-typescript#enums

I think you'll need to change to `linkTokenCreate` call like :
```ts
const  hrisCategory = {
  value: Merge.HRIS.CategoriesEnumValues.Hris,
  rawValue: "hris"
};
const response = await linkApi.linkTokenCreate({
  endUserDetailsRequest: {
    end_user_email_address: "test@email.com",
    end_user_organization_name: "Test",
    end_user_origin_id: "test",
    categories: [hrisCategory],
  },
})
```

**Comment by leewang0** [comment]
Thank you for your suggestion @f-huang , that is correct. We changed all of our enums to be wrapped in `value, rawValue` interfaces. I'd like to go into the reasoning a little bit:

* Merge unifies multiple API's and we try to unify enum values as well
* We feel that we have a pretty comprehensive mapping, but because we are not the source of truth sometimes enum values will come back with a new, not-yet-seen value
* We could either hide it completely, or return it as-is in our API
* Since we chose the latter, it requires enums in all of our SDKs to handle dynamic behavior
* Typescript string enums were actually a later feature than I would have thought, and they do not allow for dynamic values out of the box so we use `MERGE_NONSTANDARD_VALUE` as the `value` property and `rawValue` as a string to capture the API result
* This is admittedly inelegant as an input value... an oversight on my part so apologies there. If there is a backwards compatible way to just send the non-wrapped enum type, that may be something we can do this quarter, but if it is backwards-incompatible to change it just for POSTs then it will have to wait until a v4.
